#!/bin/sh
# /etc/init.d/teleirc-networkname 
# teleirc	initscript for the teleirc bot
#		Copr. 2017 by Vaasa Hacklab <info@vaasa.hacklab.fi>
### BEGIN INIT INFO
# Provides:          teleirc-networkname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Telegram-IRC gateway bot
# Description:       Provides gateway between Telegram-groups and IRC-channels
### END INIT INFO

IRCNET=networkname
DIR=/home/telebot
DAEMON=$DIR/teleirc/bin/teleirc
DAEMON_NAME=teleirc-$IRCNET
DAEMON_USER=telebot
DAEMON_GROUP=telebot
DAEMON_OPTS="-c $DIR/$IRCNET/config.js"
PIDFILE=/var/run/teleirc-$IRCNET.pid

test -f ${DAEMON} || exit 0

. /lib/lsb/init-functions

do_start () {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON --chuid $DAEMON_USER --chdir $DIR/$IRCNET/ -- $DAEMON_OPTS
	log_end_msg $?
}
do_stop () {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
